# shoulder_pan_joint: 0.0
# shoulder_lift_joint: -1.57
# elbow_joint: 0.0
# wrist_1_joint: -1.57
# wrist_2_joint: 0.0
# wrist_3_joint: 0.0


shoulder_pan_joint: 0.0        # Rotate base if needed
shoulder_lift_joint: -1.45     # Lower shoulder ~ -83°
elbow_joint: -1.40              # Raise elbow ~ +80°
wrist_1_joint: 0.0             # Keep straight
wrist_2_joint: -1.57           # Pitch wrist down (face forward)
wrist_3_joint: 0.0             # Keep camera upright
